"""Add image filename columns

Revision ID: 3b328d021477
Revises: 38ff9dd80d30
Create Date: 2024-12-05 23:35:02.730519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b328d021477'
down_revision = '38ff9dd80d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image1_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image2_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image3_filename', sa.String(length=200), nullable=True))
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('image3_filename')
        batch_op.drop_column('image2_filename')
        batch_op.drop_column('image1_filename')

    # ### end Alembic commands ###
